package main

import (
	"go-music-api/config"
	_ "go-music-api/docs" // docs generated by Swag
	"go-music-api/migrations"
	"log"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"

	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"

	"go-music-api/controllers"
	"go-music-api/repositories"
	"go-music-api/services"
)

// @title Music API
// @version 1.0
// @description API sederhana untuk mengelola koleksi musik
// @host localhost:8080
// @BasePath /
func main() {

	if err := godotenv.Load(); err != nil {
		log.Println("Tidak menemukan file .env")
	}

	config.InitDB()

	migrations.RunMigrate()

	r := gin.Default()

	// init layer
	repo := repositories.NewMusicRepository()
	service := services.NewMusicService(repo)
	controller := controllers.NewMusicController(service)

	// routes
	r.GET("/musics", controller.GetMusics)
	r.GET("/musics/:id", controller.GetMusicById)
	r.POST("/musics", controller.CreateMusic)
	r.PUT("/musics/:id", controller.UpdateMusic)
	r.DELETE("/musics/:id", controller.DeleteMusic)

	// swagger docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":8080")
}
